from handlers.message import handler as message_handler
from handlers.presence import handler as presence_handler
from handlers.iq import discovery_request_handler, registration_form_handler, registration_request_handler